services:
  jj-db:
    image: postgres:17-alpine
    container_name: jj-banking-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - jj-data:/var/lib/postgresql/data

  jj-api:
    build: .
    container_name: jj-banking-api
    ports:
      - "5000:8080"
    environment:
      # O .NET mapeia automaticamente o "__" para ":" do appsettings
      - ConnectionStrings__DefaultConnection=Host=jj-db;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
    depends_on:
      - jj-db

volumes:
  jj-data: